# Generated by Django 5.1.2 on 2024-11-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_enrollment_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
